spring:
  jpa:
    database: default
  application:
    name: job-service
  profiles:
    active: dev
  banner:
    location: classpath:banner.txt
    charset: UTF-8
server:
  servlet:
    context-path: /job
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER},http://localhost:8761/eureka/