spring:
  jpa:
    database: default
  application:
    name: job-service
  profiles:
    active: ${profilename}
  banner:
    location: classpath:banner.txt
    charset: UTF-8
server:
  servlet:
    context-path: /job
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true