version: "3.9"

services:
  registry-service:
    image: registrysevice
    container_name: RegistryServiceContainer
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - docyard-be_default
#
#  doc-handling-service:
#    image: dochandelingservice:${TAG}
##    environment:
##      - JAVA_OPTS=
##      - EUREKA_SERVER=http://registry-service:8761/eureka/
#    container_name: DocServiceContainer
#    build:
#      context: ./doc-handling-service
#      dockerfile: Dockerfile
#    depends_on:
#      - registry-service
#    ports:
#      - "8084:8084"
#    networks:
#      - docyard-be_default
#
#  authentication-service:
#    image: authenticationservice:${TAG}
##    environment:
##      - JAVA_OPTS=
##      - EUREKA_SERVER=http://registry-service:8761/eureka/
#    container_name: authServiceContainer
#    build:
#      context: ./authentication-service
#      dockerfile: Dockerfile
#    depends_on:
#      - registry-service
#    ports:
#      - "8081:8081"
#    networks:
#      - docyard-be_default
#
#  cron-job-service:
#    image: cronjobservice:${TAG}
##    environment:
##      - JAVA_OPTS=
##      - EUREKA_SERVER=http://registry-service:8761/eureka/
#    container_name: CronServiceContainer
#    build:
#      context: ./cron-job-service
#      dockerfile: Dockerfile
#    depends_on:
#      - registry-service
#    ports:
#      - "8085:8085"
#    networks:
#      - docyard-be_default
#
#  um-service:
#    image: umservice:${TAG}
##    environment:
##      - JAVA_OPTS=
##      - EUREKA_SERVER=http://registry-service:8761/eureka/
#    container_name: UmServiceContainer
#    build:
#      context: ./um-service
#      dockerfile: Dockerfile
#    depends_on:
#      - registry-service
#    ports:
#      - "8083:8083"
#    networks:
#      - docyard-be_default
#
#  gateway-service:
#    image: gatewayservice:${TAG}
##    environment:
##      - JAVA_OPTS=
##        - EUREKA_SERVER=http://registry-service:8761/eureka/
#    container_name: GatewayServiceContainer
#    build:
#      context: ./gateway-service
#      dockerfile: Dockerfile
#    depends_on:
#      - registry-service
#    ports:
#      - "8080:8080"
#    networks:
#      - docyard-be_default

networks:
  docyard-be_default:
