spring:
  jpa:
    database: default
  application:
    name: um-service
  profiles:
    active: dev
  banner:
    location: classpath:banner.txt
    charset: UTF-8
server:
  servlet:
    context-path: /um
infotech:
  gw:
    oauth:
      clientSecret: oauth
      clientId: oauth
      refreshTokenValidity: '240000'
      accessTokenValidity: '30000'
      resource:
        token-info-uri: http://authentication-service/oauth/check_token
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER},http://localhost:8761/eureka/