spring:
  profiles:
    active: dev
  application:
    name: um-service
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  jpa:
    databases: default
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
infotech:
  gw:
    oauth:
      clientId: oauth
      clientSecret: oauth
      accessTokenValidity: 30000
      refreshTokenValidity: 240000
    resource:
      token-info-uri: http://authentication-service/oauth/check_to
