server:
  port: 8080
spring:
  application:
    name: GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: UM-SERVICE
          uri: lb://UM-SERVICE
          predicates:
            - Path=/um/**
          filters:
            - AuthFilter
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/oauth/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    discovery:
      enabled: true
eureka:
  client:
    allow-redirects: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

infotech:
  gw:
    oauth:
      clientId: docyard
      clientSecret: docyard
    services:
      authentication: authentication-service