spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  banner:
    location: classpath:banner.txt
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: um-service
          uri: lb://um-service
          predicates:
            - Path=/um/un-auth/**
        - id: um-service
          uri: lb://um-service
          predicates:
            - Path=/um/**
          filters:
            - AuthFilter
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/oauth/**
        - id: doc-handling-service
          uri: lb://doc-handling-service
          predicates:
            - Path=/dl/**
          filters:
            - AuthFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    discovery:
      enabled: true

eureka:
  client:
    allow-redirects: true
    fetch-registry: true
infotech:
  gw:
    oauth:
      clientId: docyard
      clientSecret: docyard
    services:
      authentication: authentication-service