server:
  port: 8080

spring:
  application:
    name: DMS-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: UM-SERVICE
          uri: lb://UM-SERVICE
          predicates:
            - Path=/um/user/**
          filters:
            - AuthFilter
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
              - Path=/oauth/**
      discovery:
        enabled: true
  #        - id: TENANT-SERVICE
  #          uri: lb://TENANT-SERVICE
  #          predicates:
  #              - Path=/tenants/**

eureka:
  client:
    allow-redirects: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

infotech:
  gw:
    oauth:
      clientId: oauth
      clientSecret: oauth
    services:
      authentication: authentication-service