spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/docyard_dev?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}