spring:
  application:
    name: authentication-service
  security:
    user:
      name: admin
      password: admin
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

infotech:
  gw:
    oauth:
      clientId: docyard
      clientSecret: docyard
      accessTokenValidity: 30000
      refreshTokenValidity: 240000
