spring:
  profiles:
    active: dev
  application:
    name: authentication-service
  security:
    user:
      name: admin
      password: admin
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true

infotech:
  gw:
    oauth:
      clientId: docyard
      clientSecret: docyard
      accessTokenValidity: 30000
      refreshTokenValidity: 240000