spring:
  application:
    name: authentication-service
  security:
    user:
      name: admin
      password: admin
server:
  port: 8484
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

infotech:
  gw:
    oauth:
      clientId: oauth
      clientSecret: oauth
      accessTokenValidity: 30000
      refreshTokenValidity: 240000
